'use client';

import React, { useState, useMemo } from 'react';
import { Fournisseur, Produit, BcLigne, BonCommande } from '../types';

interface CreateBcDialogProps {
  isOpen: boolean;
  onClose: () => void;
  fournisseurs: Fournisseur[];
  produits: Produit[];
  onSave: (newBc: Omit<BonCommande, 'id' | 'created_at' | 'signatures'>) => void;
  existingBcCount: number;
}

interface RowSelectionState {
  selected: boolean;
  qty: number;
}

export const CreateBcDialog: React.FC<CreateBcDialogProps> = ({
  isOpen,
  onClose,
  fournisseurs,
  produits,
  onSave,
  existingBcCount,
}) => {
  const currentYear = new Date().getFullYear();
  const autoGeneratedRef = useMemo(() => {
    const num = String(existingBcCount + 1).padStart(3, '0');
    return `BC-${currentYear}-${num}`;
  }, [existingBcCount, currentYear]);

  const [selectedFournisseurId, setSelectedFournisseurId] = useState<string>(
    fournisseurs[0]?.id || ''
  );
  const [dateCommande, setDateCommande] = useState<string>(
    new Date().toISOString().slice(0, 10)
  );
  const [dateLivraison, setDateLivraison] = useState<string>(
    new Date().toISOString().slice(0, 10)
  );

  // État local de sélection des articles et quantités
  const [rowStates, setRowStates] = useState<Record<string, RowSelectionState>>(() => {
    const initial: Record<string, RowSelectionState> = {};
    produits.forEach((p, idx) => {
      initial[p.id] = {
        selected: idx === 0, // Par défaut cocher le premier article pour fluidité
        qty: idx === 0 ? 10 : 1,
      };
    });
    return initial;
  });

  const [searchTerm, setSearchTerm] = useState('');

  // Filtrage des produits pour la recherche rapide
  const filteredProduits = useMemo(() => {
    if (!searchTerm.trim()) return produits;
    const q = searchTerm.toLowerCase();
    return produits.filter(
      (p) => p.name.toLowerCase().includes(q) || p.code.toLowerCase().includes(q)
    );
  }, [produits, searchTerm]);

  // Calcul dynamique des lignes sélectionnées et des totaux
  const { selectedLignes, totalGeneralTtc } = useMemo(() => {
    const lignes: BcLigne[] = [];
    let total = 0;

    produits.forEach((p) => {
      const state = rowStates[p.id];
      if (state && state.selected && state.qty > 0) {
        const puTtc = p.priceAchatUcd || 0;
        const totalLigne = state.qty * puTtc;
        total += totalLigne;

        lignes.push({
          produit_id: p.id,
          code_produit: p.code,
          nom_produit: p.name,
          ucd: p.ucd || 'Carton',
          stock_actuel_ucd: p.stockMagasin || 0,
          qte_commande: state.qty,
          qte_recue: 0,
          pu_ttc: puTtc,
          total_ligne: totalLigne,
        });
      }
    });

    return { selectedLignes: lignes, totalGeneralTtc: total };
  }, [produits, rowStates]);

  if (!isOpen) return null;

  const handleToggleSelect = (prodId: string) => {
    setRowStates((prev) => {
      const current = prev[prodId] || { selected: false, qty: 1 };
      return {
        ...prev,
        [prodId]: {
          ...current,
          selected: !current.selected,
        },
      };
    });
  };

  const handleQtyChange = (prodId: string, value: string) => {
    const parsed = parseFloat(value) || 0;
    setRowStates((prev) => {
      const current = prev[prodId] || { selected: true, qty: 0 };
      return {
        ...prev,
        [prodId]: {
          ...current,
          selected: parsed > 0 ? true : current.selected,
          qty: parsed >= 0 ? parsed : 0,
        },
      };
    });
  };

  const handleSave = () => {
    if (selectedLignes.length === 0) {
      alert(
        'Veuillez cocher au moins un produit et saisir une quantité en UCD supérieure à 0.'
      );
      return;
    }

    const fournisseur = fournisseurs.find((f) => f.id === selectedFournisseurId) || {
      id: selectedFournisseurId,
      code: 'FOURN-001',
      name: 'IMPORT-EXPORT BÉNIN SÀRL',
    };

    onSave({
      reference: autoGeneratedRef,
      fournisseur_id: fournisseur.id,
      fournisseur_nom: fournisseur.name,
      date_commande: dateCommande,
      date_livraison_prevue: dateLivraison,
      statut: 'En attente Signature Gestionnaire',
      total_ttc: totalGeneralTtc,
      lignes: selectedLignes,
    });

    onClose();
  };

  const formatFcfa = (val: number) => {
    return new Intl.NumberFormat('fr-FR').format(Math.round(val)) + ' FCFA';
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/80 backdrop-blur-sm p-4 overflow-y-auto">
      {/* Dialog container style shadcn/ui */}
      <div className="bg-white w-full max-w-5xl rounded-3xl shadow-2xl border border-slate-200 overflow-hidden flex flex-col max-h-[92vh] animate-in fade-in zoom-in-95 duration-150">
        
        {/* Header Dialog */}
        <div className="bg-slate-900 text-white p-5 flex items-center justify-between border-b border-slate-800">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 rounded-xl bg-indigo-600 flex items-center justify-center font-bold shadow-lg shadow-indigo-600/30">
              🛒
            </div>
            <div>
              <h2 className="text-base font-extrabold tracking-tight text-white flex items-center gap-2">
                Nouveau Bon de Commande
                <span className="text-[10px] uppercase font-mono px-2 py-0.5 rounded-full bg-indigo-500/20 text-indigo-300 border border-indigo-500/30">
                  Norme UCD Bénin
                </span>
              </h2>
              <p className="text-xs text-slate-400">
                Génération officielle de bon d'achat fournisseur avec double signature électronique.
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-white text-lg font-bold p-1 leading-none rounded-lg hover:bg-slate-800 transition"
          >
            ✕
          </button>
        </div>

        {/* Ligne 1 : Fournisseur, DatePicker, Référence Readonly (BC-YYYY-NNN) */}
        <div className="p-5 bg-slate-50 border-b border-slate-200 grid grid-cols-1 sm:grid-cols-3 gap-4 text-xs">
          <div>
            <label className="block font-bold text-slate-700 mb-1">
              Fournisseur <span className="text-rose-500">*</span>
            </label>
            <select
              value={selectedFournisseurId}
              onChange={(e) => setSelectedFournisseurId(e.target.value)}
              className="w-full p-2.5 bg-white border border-slate-300 rounded-xl font-bold text-slate-800 focus:outline-none focus:ring-2 focus:ring-indigo-500"
            >
              {fournisseurs.map((f) => (
                <option key={f.id} value={f.id}>
                  [{f.code}] {f.name}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="block font-bold text-slate-700 mb-1">
              Date de Commande <span className="text-rose-500">*</span>
            </label>
            <input
              type="date"
              value={dateCommande}
              onChange={(e) => setDateCommande(e.target.value)}
              className="w-full p-2.5 bg-white border border-slate-300 rounded-xl font-bold text-slate-800 focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </div>

          <div>
            <label className="block font-bold text-slate-700 mb-1">
              Référence (Générée automatiquement)
            </label>
            <input
              type="text"
              readOnly
              value={autoGeneratedRef}
              className="w-full p-2.5 bg-slate-200/80 border border-slate-300 rounded-xl font-mono font-black text-indigo-900 cursor-not-allowed select-none"
            />
          </div>
        </div>

        {/* Body : DataTable (Source SELECT * FROM produits) */}
        <div className="p-5 overflow-y-auto flex-1 space-y-3 text-xs">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <div className="flex items-center space-x-2">
              <span className="font-black text-slate-800 uppercase tracking-wide">
                Articles en Stock éligibles à la commande :
              </span>
              <span className="bg-indigo-100 text-indigo-800 font-bold px-2 py-0.5 rounded-full text-[10px]">
                {selectedLignes.length} article(s) sélectionné(s)
              </span>
            </div>
            <input
              type="text"
              placeholder="Filtrer par nom ou code produit..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="p-2 border border-slate-300 rounded-xl text-xs w-64 bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </div>

          <div className="border border-slate-200 rounded-2xl overflow-hidden shadow-sm bg-white">
            <table className="w-full text-left text-xs border-collapse">
              <thead className="bg-slate-100 text-slate-700 font-bold border-b border-slate-200">
                <tr>
                  <th className="p-3 text-center w-12">Choix</th>
                  <th className="p-3 w-28 font-mono">Code</th>
                  <th className="p-3">Nom Produit & Catégorie</th>
                  <th className="p-3 text-center w-36">Stock Actuel (UCD)</th>
                  <th className="p-3 text-center w-36">Qté Commande (UCD)</th>
                  <th className="p-3 text-right w-32">PU TTC</th>
                  <th className="p-3 text-right w-36">Total TTC Ligne</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {filteredProduits.map((p) => {
                  const state = rowStates[p.id] || { selected: false, qty: 1 };
                  const puTtc = p.priceAchatUcd || 0;
                  const lineTotal = state.selected ? state.qty * puTtc : 0;

                  return (
                    <tr
                      key={p.id}
                      className={`transition ${
                        state.selected ? 'bg-indigo-50/50 font-medium' : 'hover:bg-slate-50 text-slate-600'
                      }`}
                    >
                      {/* Checkbox */}
                      <td className="p-3 text-center">
                        <input
                          type="checkbox"
                          checked={state.selected}
                          onChange={() => handleToggleSelect(p.id)}
                          className="w-4 h-4 rounded text-indigo-600 focus:ring-indigo-500 cursor-pointer"
                        />
                      </td>

                      {/* Code */}
                      <td className="p-3 font-mono font-bold text-slate-800">
                        {p.code}
                      </td>

                      {/* Nom Produit */}
                      <td className="p-3">
                        <span className="font-bold text-slate-900 block">{p.name}</span>
                        <span className="text-[10px] text-slate-500">
                          Unité: <strong className="text-indigo-700">{p.ucd}</strong> (1 {p.ucd} = {p.coef} {p.uv})
                        </span>
                      </td>

                      {/* Stock Actuel en UCD */}
                      <td className="p-3 text-center">
                        <span className="font-mono font-bold text-slate-800 bg-slate-100 px-2 py-1 rounded-lg">
                          {p.stockMagasin} {p.ucd}
                        </span>
                        <span className="block text-[10px] text-slate-400 mt-0.5">
                          ({p.stockMagasin * p.coef} {p.uv})
                        </span>
                      </td>

                      {/* Input Qté Commande */}
                      <td className="p-3 text-center">
                        <div className="flex items-center justify-center space-x-1">
                          <input
                            type="number"
                            min="0"
                            step="any"
                            value={state.qty}
                            disabled={!state.selected}
                            onChange={(e) => handleQtyChange(p.id, e.target.value)}
                            className={`w-24 p-1.5 text-center font-mono font-bold border rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
                              state.selected
                                ? 'bg-white border-indigo-300 text-indigo-900'
                                : 'bg-slate-100 border-slate-200 text-slate-400 cursor-not-allowed'
                            }`}
                          />
                          <span className="text-[10px] font-bold text-slate-500">
                            {p.ucd}
                          </span>
                        </div>
                      </td>

                      {/* PU TTC */}
                      <td className="p-3 text-right font-mono font-semibold text-slate-700">
                        {formatFcfa(puTtc)}
                      </td>

                      {/* Total TTC Ligne */}
                      <td className="p-3 text-right font-mono font-black text-indigo-900">
                        {formatFcfa(lineTotal)}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>

        {/* Footer : Règle B.1 + TOTAL GÉNÉRAL TTC + Boutons [Annuler] [Enregistrer] */}
        <div className="p-5 bg-slate-100 border-t border-slate-200 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center space-x-2 bg-amber-500/10 border border-amber-500/30 px-3 py-1.5 rounded-xl">
            <span className="text-amber-600 font-black text-xs">⚠️ Règle B.1 :</span>
            <span className="text-[11px] font-semibold text-amber-900">
              Commande et Réception <strong>TOUJOURS en UCD</strong> (Stock Magasin incrémenté en UCD).
            </span>
          </div>

          <div className="flex items-center space-x-4">
            <div className="text-right">
              <span className="block text-[10px] font-bold uppercase text-slate-500">
                TOTAL GÉNÉRAL TTC
              </span>
              <span className="font-mono font-black text-xl text-indigo-950">
                {formatFcfa(totalGeneralTtc)}
              </span>
            </div>

            <div className="flex items-center space-x-2">
              <button
                type="button"
                onClick={onClose}
                className="px-4 py-2.5 text-xs font-bold text-slate-600 hover:bg-slate-200 rounded-xl transition"
              >
                Annuler
              </button>
              <button
                type="button"
                onClick={handleSave}
                className="px-6 py-2.5 bg-indigo-600 hover:bg-indigo-700 active:scale-95 text-white rounded-xl text-xs font-black shadow-lg shadow-indigo-600/30 flex items-center space-x-1.5 transition"
              >
                <span>💾 Enregistrer le BC</span>
              </button>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
};
